- name: install pre-requisite packages
  apt:
    update_cache: yes
    pkg:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg
        - lsb-release


- name: download docker public key
  get_url: 
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /root/gpg-docker

- name: add docker public key
  shell: gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg /root/gpg-docker 

- name: add docker gpg
  shell: echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null

- name: install docker
  apt:
    update_cache: yes
    pkg:
        - docker-ce 
        - docker-ce-cli 
        - containerd.io
